version: "3"
services:
  my-node-app:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    env_file:
      - .env
      - ./configs/env/dev.env
    volumes:
    - .:/home/app/
    - /home/app/node_modules